<?php

namespace mosinas\GoogleService;

use Illuminate\Support\ServiceProvider;

class YoutubeAnalyticsServiceProvider extends ServiceProvider
{
    public function boot()
    {

    }


    public function register()
    {
        if ($this->app->runningInConsole()) {

            $this->publishes([
                __DIR__.'/config/config.php' => config_path('youtube_analytics.php'),
            ], 'config');

        }
    }


    public function provides()
    {
        return parent::provides(); // TODO: Change the autogenerated stub
    }
}
