<?php

namespace mosinas\GoogleService;

use Illuminate\Support\ServiceProvider;

class YoutubeAnalyticsServiceProvider extends ServiceProvider
{
    public function boot()
    {

    }


    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }


    public function provides()
    {
        return parent::provides(); // TODO: Change the autogenerated stub
    }
}
